### ISSUE TITLE
Dict kwargs recursive wrapping breaks reference assignment

### ISSUE THREAD

**Issue by pohmelie** [mewwts/addict#95] opened 2017-06-22 13:07 UTC
After #92 you can't make reference from `Dict` to `Dict` when creating instance:
``` python
>>> from addict import Dict
>>> d = Dict(a=1, b=2)
>>> a = Dict(d=d)
>>> a.d
{'a': 1, 'b': 2}
>>> d
{'a': 1, 'b': 2}
>>> a.d is d
False
>>>
```
I expect, that changes to `a.d` will affect `d`.

**Comment by egao1980** [comment] 2017-11-17 09:56
This is more of documentation issue than a bug. 
Dict() copies dict/list/tuple structure so this is expected behaviour. 

def test_recursive_wrapping_refs(self):
        d = Dict(a=1, b=2)
        a = Dict(d=d)
        c = Dict(d=d)
        c.d.z = 3

        self.assertDictEqual(a.d, d)
        self.assertDictContainsSubset(d, c.d)
        self.assertIsNot(a.d, d)
        self.assertIsNot(c.d, d)

**Comment by pohmelie** [comment] 2017-11-17 10:40
It is implicit copying. Don't you think explicit using of `copy` module will be more pythonic, so `Dict` behavior will be closer to `dict`.

**Comment by pohmelie** [comment] 2017-11-17 10:51
Also, this creates disambiguations:
``` python
>>> import addict
>>> addict.__version__
'2.1.1'
>>> from addict import Dict
>>> l = [1, 2, 3]
>>> d = Dict(l=l)
>>> d.l
[1, 2, 3]
>>> d.l is l
False
>>> d.l = l
>>> d.l is l
True
>>>
```

**Comment by mewwts** [comment] 2017-11-18 10:14
Hey @pohmelie,
 
I understand that the behavior is a bit confusing. It's an attempt to balance between expectations of the `addict` module. Today, whatever you give `addict` in the constructor will be recursively iterated over and any `dict` will be turned into a `Dict`. In contrast, whatever you set as an attribute on the `Dict` instance will _not_ be copied.  While this is the way we intended it to work, it can lead to surprises. 

At this point, I am leaning towards moving today's `__init__`-functionality in it's own static method, say `Dict.from_dict`, and let `__init__` do as you expect over. This would however warrant a major release. 

Thanks @egao1980 for stepping in and answering questions! 👍

**Closed** 2018-12-20 06:15 UTC

**Comment by hellocoldworld** [comment] 2020-12-03 18:39
hello @mewwts is the new `from_dict` method already available? I think it could greatly improve the reading of the code, so if it's not done, I think it would be a great idea!
